name: Skicka dagliga nyheter

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"   # var 2:e minut (UTC)
  workflow_dispatch:

jobs:
  send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checka ut koden
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installera dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: KÃ¶r nyheter-script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python DagensNyheter.py
